development:
   adapter: mysql2
   database: chat
   username: root
   password: root
   host: localhost

test:
   adapter: mysql2
   database: chat
   username: root
   password: root
   host: localhost

production:
   adapter: mysql2
   database: <%= ENV["DB_DATABASE"] %>
   username: <%= ENV["DB_USER"] %>
   password: <%= ENV["DB_PASSWORD"] %>
   host: <%= ENV["DB_HOST"] %>
